name: buzz_tech

description: "A small cross-platform application designed to record tasks and receive notifications about them."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
#* for ui fetures
  flutter_svg: ^2.0.10+1
  awesome_snackbar_content: ^0.1.4
  flutter_animate: ^4.5.0

#* for Bloc 
  flutter_bloc: ^9.0.0
  bloc_test: ^10.0.0
  equatable: ^2.0.5

#* Logic
  uuid: ^4.5.1
  intl: ^0.19.0
  #* Notifications
  timezone: ^0.10.0
  #* Android/ios
  flutter_local_notifications: ^18.0.1
  #* Windows
  local_notifier: ^0.1.6

#* Storage
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/HomeFrame.png
    - lib/assets/icons/Category=Event.svg
    - lib/assets/icons/Category=Goal.svg
    - lib/assets/icons/Category=Task.svg