name: bloc_to_do

#! 'Add here a normal description'
description: ""

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

#* for ui fetures
  flutter_svg: ^2.0.10+1
  awesome_snackbar_content: ^0.1.4
  flutter_animate: ^4.5.0

#* for Bloc 
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  equatable: ^2.0.5

#* Logic
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
#* Storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/HomeFrame.png
    - lib/assets/icons/Category=Event.svg
    - lib/assets/icons/Category=Goal.svg
    - lib/assets/icons/Category=Task.svg